// src/config/permissions.js

export const ROLES = {
    SUPER_ADMIN: 'super_admin',
    ADMIN: 'admin',
    GERENTE: 'gerente',
    JEFE_TALLER: 'jefe_taller',
    ADMINISTRATIVO: 'administrativo',
    OPERARIO: 'operario'
};

export const PERMISOS = {
    // 👇 LA LLAVE QUE FALTABA PARA EL SAAS 👇
    SAAS_CREAR_EMPRESA: [ROLES.SUPER_ADMIN],

    // --- LECTURA DE MÓDULOS ---
    CATALOGOS_LEER: Object.values(ROLES),
    INVENTARIO_LEER: Object.values(ROLES),
    ENTIDADES_LEER: Object.values(ROLES),
    OT_LEER: Object.values(ROLES),
    COTIZACIONES_LEER: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.GERENTE, ROLES.JEFE_TALLER, ROLES.ADMINISTRATIVO],

    // --- ACCIONES ESPECÍFICAS ---
    CATALOGOS_ESCRIBIR: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.GERENTE, ROLES.JEFE_TALLER, ROLES.ADMINISTRATIVO],
    INVENTARIO_MOVER: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.GERENTE, ROLES.JEFE_TALLER, ROLES.ADMINISTRATIVO],
    INVENTARIO_INICIALIZAR: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.GERENTE, ROLES.JEFE_TALLER],
    ENTIDADES_ESCRIBIR: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ADMINISTRATIVO],
    COTIZACIONES_ESCRIBIR: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.JEFE_TALLER, ROLES.ADMINISTRATIVO],
    OT_GESTION_MAESTRA: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.GERENTE, ROLES.JEFE_TALLER, ROLES.ADMINISTRATIVO],
    OT_OPERACION_TALLER: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.GERENTE, ROLES.JEFE_TALLER]
};

export const tienePermiso = (userRole, accionPermitida) => {
    if (!userRole) return false;
    return accionPermitida.includes(userRole);
};